Add Work and About Us Section
shella12/protofolio pull request #3
Opened 2022-07-01 14:59 UTC by shella12

#Added Work Section and About Us Section
- Edited HTML
- Edited CSS

2022-07-01 17:07 UTC, cwaku requested changes
Hi @shella12 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
There are a few issues 🐛  that you still need to work 🛠️  on to go to the next project ⏭️  but you are almost there! 🏃🏾 

## Highlights
- [x] Good overall template design 👍🏾 
- [x] Linters passed 💯 
- [x] Correct use of Github flow 🥇 
- [ ] Meaningful PR title 👍🏾 
- [ ] Personalised custom README ✔️ 

## Required Changes ♻️
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips 🌟  that can improve your code quality 💯 and help you get a better job 💼.

I will guide 📔 you through fixing 🛠️ these bugs, follow my comments down below and make sure you don't miss any of them, in order to get your project approved ✅

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 17:07 UTC, cwaku commented on index.html
> +    <section class="work">
- [x] It is a requirement that you align the main container of the projects with the `display: grid` CSS property. Kindly fix that.

2022-07-01 17:07 UTC, cwaku commented on style.css
> +}
- [x] It is a requirement that you align the content of each project with flexbox. Kindly fix that.

2022-07-01 17:07 UTC, cwaku commented on index.html
> +            </div>
- [x] I suggest you have the list of the technologies in a `ul` and each of them a `li`. This is part of the core requirements.

2022-07-01 17:07 UTC, cwaku commented on index.html
> +                <span>Python</span>
- [x] On the Figma template, there are only three technologies per project but it happens you have more than that. This is totally alright but it seems to be creating a problem where all of the technologies are not appropriately aligned. Kindly either tweak the CSS to align them as seen in the design or remove the extra altogether.
- [x] While you are at it, kindly confirm that the size of the technologies matches that of the Figma design.

Figma Design | Your Design
-- | --
![image](https://user-images.githubusercontent.com/29071984/176937750-71d35c09-ad1d-440e-af9a-3b71a54bf3ec.png) | ![image](https://user-images.githubusercontent.com/29071984/176937870-61963378-487e-4151-a3a9-03fec6a0e220.png)

2022-07-01 17:07 UTC, cwaku commented on index.html
> +        </div>
- [ ] The button (e.g., "Get my CV") should be a link `a` or `button` tag and follows the button styling: Active, Hover and Pressed. I suggest you have that fixed.

![image](https://user-images.githubusercontent.com/29071984/176938762-599f0a62-030f-4018-969a-b78bb551fd29.png)

2022-07-02 08:20 UTC, wuletawwonte approved these changes
## STATUS: APPROVED ♻️♻️
Hi @shella12 👋🏿👋🏿👋🏿, 

Great work on making the changes requested by a previous reviewer :clap:
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/bedaa87cf63a4eb642948910de3563599306694dfb7118796862f47e55d90651/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f546466794b724e3748475449592f67697068792e676966)

## TO HIGHLIGHT: 
- Your project is professional ✔️ 
- Correct Github Flow ✔️
- Your PR has a proper title and description ✔️
- Nice commit history ✔️
- Well structured files ✔️ 

## Required Changes ♻️
_Please check the comments under the review as well._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-02 08:20 UTC, wuletawwonte commented on style.css
> +}
- [ ] [OPTIONAL] Please make sure the list of tech stacks is laid out properly. The Figma design is a bit different from your output.

2022-07-02 09:32 UTC, merged